### ISSUE TITLE
Unable to run qtrio.py

### ISSUE THREAD

**Issue by gordon-epc** [altendky/qtrio#256]
I was unable to run the `/qtrio/examples/readme/qtrio.py` python script. I receive the error message:

```
Traceback (most recent call last):
  File "C:\Projects\qtrio\qtrio\examples\readme\qtrio.py", line 8, in <module>
    import qtrio
  File "C:\Projects\qtrio\qtrio\examples\readme\qtrio.py", line 9, in <module>
    import qtrio.dialogs
ModuleNotFoundError: No module named 'qtrio.dialogs'; 'qtrio' is not a package
```

If I change the filename from `qtrio.py` to `qtrio_ex.py`, I no longer get the error and the script works as expected.

**Comment by altendky** [comment]
Thanks Python for adding the script's directory to `sys.path`...
