### ISSUE TITLE
Local CI testing instructions missing cffi install

### ISSUE THREAD

**Issue by gordon-epc** [altendky/qtrio#259]
Following the [local CI testing instructions](https://qtrio.readthedocs.io/en/stable/development/testing.html#testing), when I run the command:

`(testvenv) C:\Projects\qtrio>pytest --pyargs qtrio`

I see the following output:
```
Traceback (most recent call last):
  File "C:\Program Files\Python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Program Files\Python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Projects\qtrio\testvenv\Scripts\pytest.exe\__main__.py", line 7, in <module>
  File "c:\projects\qtrio\testvenv\lib\site-packages\_pytest\config\__init__.py", line 185, in console_main
    code = main()
  File "c:\projects\qtrio\testvenv\lib\site-packages\_pytest\config\__init__.py", line 143, in main
    config = _prepareconfig(args, plugins)
  File "c:\projects\qtrio\testvenv\lib\site-packages\_pytest\config\__init__.py", line 319, in _prepareconfig
    pluginmanager=pluginmanager, args=args
  File "c:\projects\qtrio\testvenv\lib\site-packages\pluggy\hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "c:\projects\qtrio\testvenv\lib\site-packages\pluggy\manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "c:\projects\qtrio\testvenv\lib\site-packages\pluggy\manager.py", line 87, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "c:\projects\qtrio\testvenv\lib\site-packages\pluggy\callers.py", line 203, in _multicall
    gen.send(outcome)
  File "c:\projects\qtrio\testvenv\lib\site-packages\_pytest\helpconfig.py", line 100, in pytest_cmdline_parse
    config: Config = outcome.get_result()
  File "c:\projects\qtrio\testvenv\lib\site-packages\pluggy\callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "c:\projects\qtrio\testvenv\lib\site-packages\pluggy\callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "c:\projects\qtrio\testvenv\lib\site-packages\_pytest\config\__init__.py", line 1003, in pytest_cmdline_parse
    self.parse(args)
  File "c:\projects\qtrio\testvenv\lib\site-packages\_pytest\config\__init__.py", line 1283, in parse
    self._preparse(args, addopts=addopts)
  File "c:\projects\qtrio\testvenv\lib\site-packages\_pytest\config\__init__.py", line 1172, in _preparse
    self.pluginmanager.load_setuptools_entrypoints("pytest11")
  File "c:\projects\qtrio\testvenv\lib\site-packages\pluggy\manager.py", line 299, in load_setuptools_entrypoints
    plugin = ep.load()
  File "c:\projects\qtrio\testvenv\lib\site-packages\importlib_metadata\__init__.py", line 178, in load
    module = import_module(match.group('module'))
  File "C:\Program Files\Python37\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "c:\projects\qtrio\testvenv\lib\site-packages\_pytest\assertion\rewrite.py", line 170, in exec_module
    exec(co, module.__dict__)
  File "c:\projects\qtrio\testvenv\lib\site-packages\pytest_trio\__init__.py", line 4, in <module>
    from .plugin import trio_fixture
  File "c:\projects\qtrio\testvenv\lib\site-packages\_pytest\assertion\rewrite.py", line 170, in exec_module
    exec(co, module.__dict__)
  File "c:\projects\qtrio\testvenv\lib\site-packages\pytest_trio\plugin.py", line 10, in <module>
    import trio
  File "c:\projects\qtrio\testvenv\lib\site-packages\trio\__init__.py", line 18, in <module>
    from ._core import (
  File "c:\projects\qtrio\testvenv\lib\site-packages\trio\_core\__init__.py", line 9, in <module>
    from ._exceptions import (
  File "c:\projects\qtrio\testvenv\lib\site-packages\trio\_core\_exceptions.py", line 3, in <module>
    from trio._util import NoPublicConstructor
  File "c:\projects\qtrio\testvenv\lib\site-packages\trio\_util.py", line 60, in <module>
    _ffi = cffi.FFI()
  File "c:\projects\qtrio\testvenv\lib\site-packages\cffi\api.py", line 48, in __init__
    import _cffi_backend as backend
ModuleNotFoundError: No module named '_cffi_backend'
```

I installed cffi and executed the test command again and the tests run as expected. Perhaps this line in the instructions should be updated:
`testvenv/bin/pip install --upgrade pip setuptools wheel cffi`

**Comment by altendky** [comment]
Hum, so it does have CFFI already just not `_cffi_backend`.  It looks like that is packaged with CFFI wheels.  Trio ought to trigger CFFI installation.

https://github.com/python-trio/trio/blob/1c37e5458ebb0e6f17d8cc576efc52890bbe8bd6/setup.py#L91
```python
        "cffi>=1.14; os_name == 'nt' and implementation_name != 'pypy'",
```

Ah...  Trio uses `os_name`.  I usually use `sys_platform`.  Anyways, the script is a bash script and Python may not be reporting `nt` in that case.  But when you run the `pip` command directly it would.  How did you run the `ci.sh` script?  We could try checking this theory by adding this to the script.

```bash
python -c 'import os; import sys; print("os.name:", os.name); print("sys.platform:", sys.platform)'
```

**Comment by gordon-epc** [comment]
First to address your comment:

I ran the following command in a normal shell and a similar command with testvenv activated and got the same results:
```
C:\Projects\qtrio>python -c "import os; import sys; print('os.name:', os.name); print('sys.platform:', sys.platform)"
os.name: nt
sys.platform: win32
```

I also added the one-liner to the ci.sh script and got this result:
```
+ python -c 'import os; import sys; print('\''os.name:'\'', os.name); print('\''sys.platform:'\'', sys.platform)'
os.name: nt
sys.platform: win32
```

I've retested to better understand why I saw the error I reported. I believe there are a couple reasons that led to that error.

1. I didn't run the install commands correctly for Windows and ignored (or didn't understand) error messages.
2. One of the install commands in the "Testing" documentation isn't correct (more below).

Given what I found, this issue should probably be renamed "Suggestions to improve 'Testing' documentation".

The command:
`testvenv/bin/pip install --editable .[pyside2,checks,docs,tests]`
should be:
`.\testvenv\Scripts\pip3 install --editable .[pyside2,p_checks,p_docs,p_tests]`
to match the definitions in `setup.py`.

The command:
`testvenv/bin/black .`
is a bit destructive! I blindly ran the command and black blew through the `testvenv` directory modifying files. Consider replacing with:
`.\testvenv\Scripts\black qtrio --check`

I'm not sure it matters, but perhaps add to the documentation running the command:
`.\testvenv\Scripts\activate`
prior to running the command:
`.\testvenv\Scripts\pip3 install --upgrade pip setuptools wheel`
The first time I run the install command, it gives an access denied error. The second time I run it, it seems to (intelligently?) skip the pip install. I'm not exactly sure what is happening.

The command:
        testvenv/bin/pytest --pyargs qtrio
surprisingly gets 4 errors on my PC. Perhaps this is a separate issue?

I realize I'm being a little loose flipping between linux and Windows syntax above. Perhaps there should be separate instructions for each OS since there are distinct syntax differences?

**Comment by altendky** [comment]
> 1. I didn't run the install commands correctly for Windows and ignored (or didn't understand) error messages.
> 2. One of the install commands in the "Testing" documentation isn't correct (more below).
> 
> Given what I found, this issue should probably be renamed "Suggestions to improve 'Testing' documentation".
> 
> The command:
> `testvenv/bin/pip install --editable .[pyside2,checks,docs,tests]`
> should be:
> `.\testvenv\Scripts\pip3 install --editable .[pyside2,p_checks,p_docs,p_tests]`
> to match the definitions in `setup.py`.

You already fixed this in https://github.com/altendky/qtrio/commit/0fe625b7db4338941850444bdbd76a7f0558c5c2#diff-43bbed07c8b45c13c4e2e53a07ea8fe528a4e727fe7362bf3e528c445c421505 but it hasn't been released yet so you would need to use the `latest` version choice (most recent commit to `main`) if looking at RTD (https://qtrio.readthedocs.io/en/latest/development/testing.html).  It defaults to `stable` (most recent version based on tags) so that users will get docs for the version they would get from `venv/bin/pip install qtrio` (https://qtrio.readthedocs.io/en/stable/development/testing.html).

With it explained now, yeah, it doesn't make a whole lot of sense to use stable documentation for development that more or less has to happen on latest instead.  I don't know offhand how to make a "version" specific warning on RTD so I guess we just make one that always shows up and encourages people to look at the latest version.  See https://github.com/altendky/qtrio/pull/261.

> The command:
> `testvenv/bin/black .`
> is a bit destructive! I blindly ran the command and black blew through the `testvenv` directory modifying files. Consider replacing with:
> `.\testvenv\Scripts\black qtrio --check`

It shouldn't do that because of the configuration in `pyproject.toml`.  We might need some more exploration on this one to figure it out.

https://github.com/altendky/qtrio/blob/bdbd0261436d3c9ca64b60a091d276778027847e/pyproject.toml#L1-L9

> I'm not sure it matters, but perhaps add to the documentation running the command:
> `.\testvenv\Scripts\activate`
> prior to running the command:
> `.\testvenv\Scripts\pip3 install --upgrade pip setuptools wheel`
> The first time I run the install command, it gives an access denied error. The second time I run it, it seems to (intelligently?) skip the pip install. I'm not exactly sure what is happening.

When updating pip on Windows you need to `python -m pip` instead of just `pip` otherwise the `pip.exe` is in use and can't be replaced.  A minimal change is proposed in https://github.com/altendky/qtrio/pull/260.  We could go further and provide explicit separate Windows commands to also account for the `bin/`/`scripts/` variations.  I hate those.  It's such a pain...

https://github.com/altendky/sundog/blame/89c0c9ede2f432ffce537bfce81ba8392408ebc9/README.rst#L47-L55
```rst
.. tab:: Unix/macOS

    .. code-block:: console

        $ myvenv/bin/pip install git+https://github.com/altendky/sundog

.. tab:: Windows

    .. code-block:: console
```

> The command:
> `testvenv/bin/pytest --pyargs qtrio`
> surprisingly gets 4 errors on my PC. Perhaps this is a separate issue?

Maybe start with a snippet in Slack and we'll go from there.

> I realize I'm being a little loose flipping between linux and Windows syntax above. Perhaps there should be separate instructions for each OS since there are distinct syntax differences?

Heh, yep, maybe.

**Comment by gordon-epc** [comment]
The black issue was user error on my part. Wrong qtrio checked out.

The pytest errors no longer occur. Again, wrong qtrio checked out.

#260 and #261 are approved.

The only item left, per a separate conversation, would be adding a note about deleting the `dist` directory prior to executing the `ci.sh` script.

**Comment by altendky** [comment]
https://github.com/altendky/qtrio/pull/263

**Comment by altendky** [comment]
Changes all merged.  Done I think?

**Comment by gordon-epc** [comment]
Yes, all done. Thanks.
