### ISSUE TITLE
Crash with qtrio 0.5.0 / qts

### ISSUE THREAD

**Issue by FredericLeRoux** [altendky/qtrio#269]
I am unable to run qtrio 0.5.0, while getting back to qtrio 0.1.0 solves the issue. I get the following msg:

installing package dependencies
Traceback (most recent call last):
File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
return _run_code(code, main_globals, None,
File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
exec(code, run_globals)
File "/home/XXX/dEAduction/src/deaduction/dui/__main__.py", line 34, in <module>
import qtrio
File "/home/XXX/.local/lib/python3.8/site-packages/qtrio/__init__.py", line 20, in <module>
from ._core import (
File "/home/XXX/.local/lib/python3.8/site-packages/qtrio/_core.py", line 15, in <module>
import qts
File "/home/XXX/.local/lib/python3.8/site-packages/qts/__init__.py", line 7, in <module>
from qts._core import (
File "/home/XXX/.local/lib/python3.8/site-packages/qts/_core.py", line 10, in <module>
@attr.frozen
AttributeError: module 'attr' has no attribute 'frozen'

(This is on Ubuntu).

**Comment by altendky** [comment]
Or I moved too quickly and it's really over in qts...  so lemme fix it there.
